pipeline{
    agent any
    stages{
        stage('Hello'){
            steps{
                 sh'''
                     echo "Hello this is groovy..."
                 '''
             }
         }
            stage('Bye'){
                 steps{
                     sh'''
                         echo "Final stage.."
                    '''
            }
        }
    }
}       