pipeline{
    agent any
    stages{
        stage('First'){
            steps{
                 sh'''
                     echo "Hello this is groovy..."
                 '''
             }
         }
            stage('updated'){
                 steps{
                     sh'''
                         echo "updtaed stage.."
                    '''
            }
        }
        stage('Last'){
            steps{
                sh'''
                    echo "This is Last Stage..."
                '''
            }
        }
        stage('second'){
            steps{
                sh'''
                    echo "this second stage"
                '''
            }
        }
    }
}       