pipeline{
    agent none
    stages{
        stage('Run Tests'){
            parallel{
                stage('Test on Windows'){
                    agent any
                    steps{
                        echo "test"
                    }
                }
                stage('Test on Linux'){
                    agent any
                    steps{
                        echo "test-2"
                    }
                }
            }
        }

        stage('Deploy satge'){
            steps{
                echo "test"
            }
        }

        stage('Deploy test'){
            stage('Test on Windows'){
                agent any
                steps{
                    echo "Testing"
                }
            }
            stage('Test on linux'){
                stpes{
                    echo "Test requires"
                }
            }
        }
    }
}