pipeline {
    agent any

    parameters {
        string(name: "ENV',defaultvalue: 'prod',description: 'This is testing...")
    }

    stages {
        stage('Build-stage') {
            stages {
                stage('checking code') {
                    steps {
                        sh 'echo "Hello world"'
                    }
                }
                stage('testing code'){
                    steps{
                        sh 'echo "Hello multi-stage"'
                    }
                }
            }

         }
         stage('Deploying one more ENV'){
            stages {
                 stage('deploy to env') {
                    stpes {
                        sh 'echo "testing indev"'
                    }
                }
            }
        }
    }
 }